name: Publish NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2.5.2
        with:
          PROJECT_FILE_PATH: Net.Bluewalk.LidlPlus/Net.Bluewalk.LidlPlus.csproj
          NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
          DOTNET_CLI_TELEMETRY_OPTOUT: 1
